version: '3.8'
services:
  skyblock_cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  skyblock_amqp:
    hostname: skyblock_amqp
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - "rabbitmq_data:/data"
    networks:
    - rabbitmq-network
volumes:
  rabbitmq_data:
  cache:
    driver: local

networks:
  rabbitmq-network:
    driver: bridge